import React, { useState } from 'react';
import axios from 'axios';
import './ExportStep.css';

export default function ExportStep({ data, template, theme, onBack }) {
  const [htmlLoading, setHtmlLoading] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [shareLoading, setShareLoading] = useState(false);
  const [shareUrl, setShareUrl] = useState('');
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');

  const payload = { portfolioData: data, templateId: template, theme };

  const downloadHtml = async () => {
    setHtmlLoading(true); setError('');
    try {
      const res = await axios.post('/api/export/html', payload, { responseType: 'blob' });
      const url = URL.createObjectURL(new Blob([res.data], { type: 'text/html' }));
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(data.name || 'portfolio').replace(/\s+/g, '-').toLowerCase()}-portfolio.html`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError('HTML export failed. Please try again.');
    }
    setHtmlLoading(false);
  };

  const downloadPdf = async () => {
    setPdfLoading(true); setError('');
    try {
      const res = await axios.post('/api/export/pdf', payload, { responseType: 'blob' });
      const url = URL.createObjectURL(new Blob([res.data], { type: 'application/pdf' }));
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(data.name || 'portfolio').replace(/\s+/g, '-').toLowerCase()}-portfolio.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError('PDF export failed. Make sure Puppeteer is installed on the server.');
    }
    setPdfLoading(false);
  };

  const createShareLink = async () => {
    setShareLoading(true); setError('');
    try {
      const res = await axios.post('/api/export/share', payload);
      setShareUrl(res.data.url);
    } catch (e) {
      setError('Could not generate share link. Please try again.');
    }
    setShareLoading(false);
  };

  const copyLink = () => {
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const skills = getSkillsFlat(data.skills);

  return (
    <div>
      <div className="card">
        <h2 className="card-title">Export your portfolio</h2>
        <p className="card-sub">Your portfolio is ready. Download it or share it with a link.</p>

        <div className="export-grid">
          <div className="export-option">
            <div className="export-icon html-icon">
              <HtmlIcon />
            </div>
            <div className="export-info">
              <div className="export-label">HTML file</div>
              <div className="export-desc">A standalone webpage you can host on GitHub Pages, Netlify, or any web host. Opens in any browser.</div>
            </div>
            <button className="btn btn-success export-btn" onClick={downloadHtml} disabled={htmlLoading}>
              {htmlLoading ? <><Spinner /> Generating...</> : 'Download HTML'}
            </button>
          </div>

          <div className="export-option">
            <div className="export-icon pdf-icon">
              <PdfIcon />
            </div>
            <div className="export-info">
              <div className="export-label">PDF file</div>
              <div className="export-desc">Print-ready PDF, perfect for job applications and email attachments. Generated by Puppeteer.</div>
            </div>
            <button className="btn btn-primary export-btn" onClick={downloadPdf} disabled={pdfLoading}>
              {pdfLoading ? <><Spinner /> Generating...</> : 'Download PDF'}
            </button>
          </div>

          <div className="export-option">
            <div className="export-icon link-icon">
              <LinkIcon />
            </div>
            <div className="export-info">
              <div className="export-label">Shareable link</div>
              <div className="export-desc">Get a public URL to share directly with recruiters on LinkedIn, email, or anywhere.</div>
            </div>
            {shareUrl ? (
              <div className="share-result">
                <div className="share-url">{shareUrl}</div>
                <button className="btn btn-sm" onClick={copyLink}>
                  {copied ? '✓ Copied!' : 'Copy'}
                </button>
              </div>
            ) : (
              <button className="btn export-btn" onClick={createShareLink} disabled={shareLoading}>
                {shareLoading ? <><Spinner /> Creating...</> : 'Create link'}
              </button>
            )}
          </div>
        </div>

        {error && <div className="error-msg" style={{ marginTop: 16 }}>{error}</div>}
      </div>

      <div className="card summary-card">
        <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 16 }}>Portfolio summary</h3>
        <div className="summary-grid">
          <SumCard label="Name" value={data.name || '—'} />
          <SumCard label="Template" value={template.charAt(0).toUpperCase() + template.slice(1)} />
          <SumCard label="Experience entries" value={(data.experience || []).length} />
          <SumCard label="Projects" value={(data.projects || []).length} />
          <SumCard label="Skills" value={skills.length} />
          <SumCard label="Achievements" value={(data.achievements || []).length} />
        </div>

        {skills.length > 0 && (
          <div style={{ marginTop: 20 }}>
            <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '.06em', marginBottom: 10 }}>Skills included</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
              {skills.map((s, i) => (
                <span key={i} style={{ fontSize: 12, padding: '3px 10px', borderRadius: 4, background: 'var(--purple-50)', color: 'var(--purple-800)', fontWeight: 500 }}>{s}</span>
              ))}
            </div>
          </div>
        )}
      </div>

      <div className="row-between">
        <button className="btn" onClick={onBack}>← Back</button>
        <div style={{ fontSize: 13, color: 'var(--text-muted)' }}>
          Portfolio built with PortfolioAI
        </div>
      </div>
    </div>
  );
}

function SumCard({ label, value }) {
  return (
    <div style={{ background: 'var(--gray-100)', borderRadius: 'var(--radius-md)', padding: '12px 16px' }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '.06em', marginBottom: 4 }}>{label}</div>
      <div style={{ fontSize: 18, fontWeight: 700, color: 'var(--text-primary)' }}>{value}</div>
    </div>
  );
}

function getSkillsFlat(skills) {
  if (!skills) return [];
  if (Array.isArray(skills)) return skills;
  return [...(skills.languages||[]),...(skills.frameworks||[]),...(skills.tools||[]),...(skills.other||[])];
}

function Spinner() {
  return <span style={{ display: 'inline-block', width: 14, height: 14, border: '2px solid rgba(255,255,255,.3)', borderTopColor: 'white', borderRadius: '50%', animation: 'spin .7s linear infinite', verticalAlign: 'middle' }} />;
}

function HtmlIcon() {
  return (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <path d="M4 4h20v20H4V4z" fill="none" stroke="#0F6E56" strokeWidth="1.5"/>
      <path d="M9 10l-4 4 4 4M19 10l4 4-4 4M16 8l-4 12" stroke="#0F6E56" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

function PdfIcon() {
  return (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <rect x="3" y="2" width="18" height="24" rx="2" stroke="#534AB7" strokeWidth="1.5"/>
      <path d="M17 2v7h7" stroke="#534AB7" strokeWidth="1.5"/>
      <path d="M7 13h10M7 17h7" stroke="#534AB7" strokeWidth="1.5" strokeLinecap="round"/>
    </svg>
  );
}

function LinkIcon() {
  return (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <path d="M12 16l-4 4a4 4 0 01-5.66-5.66l3-3" stroke="#185FA5" strokeWidth="1.5" strokeLinecap="round"/>
      <path d="M16 12l4-4a4 4 0 00-5.66-5.66l-3 3" stroke="#185FA5" strokeWidth="1.5" strokeLinecap="round"/>
      <path d="M10 18l8-8" stroke="#185FA5" strokeWidth="1.5" strokeLinecap="round"/>
    </svg>
  );
}
